name:  Báo cáo Camera
description: Mẫu báo cáo tình trạng camera hằng ngày
title: "[Báo cáo] Camera - {{ date }}"
labels: ["report", "camera"]
 
body:
  - type: markdown
    attributes:
      value: |
        #  Báo cáo tình trạng Camera
        Vui lòng chọn thông tin chi tiết bên dưới để tạo báo cáo.
 
  - type: input
    id: datetime
    attributes:
      label: 🕒 Ngày giờ báo cáo
      description: Nhập thời điểm lập báo cáo (dd/mm/yyyy hh:mm)
      placeholder: 01/01/2026 17:13
 
  - type: dropdown
    id: camera_name
    attributes:
      label:  Tên camera
      description: Chọn tên camera từ danh sách
      options:
        - Camera cầu cân
        - Camera kho
        - Camera khu vực A
        - Camera khu vực B
        - Camera cổng chính
        - Camera nhà xe
 
  - type: dropdown
    id: status
    attributes:
      label:  Tình trạng hiện tại
      options:
        -  Hoạt động bình thường
        -  Mất tín hiệu
        -  Đang bảo trì
 
  - type: input
    id: lost_time
    attributes:
      label:  Thời điểm mất tín hiệu
      description: Nếu có sự cố, nhập thời gian mất tín hiệu
      placeholder: 01/01/2026 17:00
 
  - type: input
    id: recovered_time
    attributes:
      label:  Thời điểm khôi phục tín hiệu
      description: Nhập thời gian camera hoạt động trở lại
      placeholder: 01/01/2026 17:30
 
